[package]
name = "jankenpon_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
serde-wasm-bindgen = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 